# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.msgtype = QtWidgets.QComboBox(self.centralwidget)
        self.msgtype.setGeometry(QtCore.QRect(320, 0, 111, 22))
        self.msgtype.setObjectName("msgtype")
        self.msgtype.addItem("")
        self.msgtype.addItem("")
        self.msgtype.addItem("")
        self.msgtype.addItem("")
        self.msgtype.addItem("")
        self.msgtype.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 61, 16))
        self.label.setObjectName("label")
        self.content = QtWidgets.QTextEdit(self.centralwidget)
        self.content.setGeometry(QtCore.QRect(0, 30, 801, 271))
        self.content.setObjectName("content")
        self.isAtAll = QtWidgets.QCheckBox(self.centralwidget)
        self.isAtAll.setGeometry(QtCore.QRect(20, 10, 80, 20))
        self.isAtAll.setObjectName("isAtAll")
        self.atMobiles = QtWidgets.QLineEdit(self.centralwidget)
        self.atMobiles.setGeometry(QtCore.QRect(0, 300, 801, 21))
        self.atMobiles.setText("")
        self.atMobiles.setObjectName("atMobiles")
        self.sendMsg = QtWidgets.QPushButton(self.centralwidget)
        self.sendMsg.setGeometry(QtCore.QRect(720, 0, 75, 24))
        self.sendMsg.setObjectName("sendMsg")
        self.robotToken = QtWidgets.QLineEdit(self.centralwidget)
        self.robotToken.setGeometry(QtCore.QRect(440, 0, 281, 21))
        self.robotToken.setObjectName("robotToken")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.msgtype.setItemText(0, _translate("MainWindow", "Text"))
        self.msgtype.setItemText(1, _translate("MainWindow", "Link"))
        self.msgtype.setItemText(2, _translate("MainWindow", "Markdown"))
        self.msgtype.setItemText(3, _translate("MainWindow", "整体跳转ActionCard"))
        self.msgtype.setItemText(4, _translate("MainWindow", "独立跳转ActionCard"))
        self.msgtype.setItemText(5, _translate("MainWindow", "FeedCard"))
        self.label.setText(_translate("MainWindow", "消息类型："))
        self.content.setPlaceholderText(_translate("MainWindow", "文本消息内容"))
        self.isAtAll.setText(_translate("MainWindow", "@所有人"))
        self.atMobiles.setPlaceholderText(_translate("MainWindow", "被@人的手机号"))
        self.sendMsg.setText(_translate("MainWindow", "发送"))
        self.robotToken.setPlaceholderText(_translate("MainWindow", "Token"))
