# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bl_download.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 731)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.downloadlink_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.downloadlink_LineEdit.setObjectName("downloadlink_LineEdit")
        self.gridLayout.addWidget(self.downloadlink_LineEdit, 0, 1, 1, 1)
        self.analy_btn = QtWidgets.QPushButton(self.centralwidget)
        self.analy_btn.setObjectName("analy_btn")
        self.gridLayout.addWidget(self.analy_btn, 0, 2, 1, 1)
        self.download_all_btn = QtWidgets.QPushButton(self.centralwidget)
        self.download_all_btn.setObjectName("download_all_btn")
        self.gridLayout.addWidget(self.download_all_btn, 0, 3, 1, 1)
        self.savepath_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.savepath_LineEdit.setObjectName("savepath_LineEdit")
        self.gridLayout.addWidget(self.savepath_LineEdit, 1, 0, 1, 2)
        self.downloadlink_table = QtWidgets.QTableWidget(self.centralwidget)
        self.downloadlink_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.downloadlink_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.downloadlink_table.setColumnCount(1)
        self.downloadlink_table.setObjectName("downloadlink_table")
        self.downloadlink_table.setRowCount(0)
        self.downloadlink_table.horizontalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.downloadlink_table, 2, 0, 1, 4)
        self.savepath_btn = QtWidgets.QPushButton(self.centralwidget)
        self.savepath_btn.setObjectName("savepath_btn")
        self.gridLayout.addWidget(self.savepath_btn, 1, 2, 1, 1)
        self.set_cookies_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_cookies_btn.setObjectName("set_cookies_btn")
        self.gridLayout.addWidget(self.set_cookies_btn, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BiliBili下载器"))
        self.label.setText(_translate("MainWindow", "视频地址："))
        self.analy_btn.setText(_translate("MainWindow", "解析"))
        self.download_all_btn.setText(_translate("MainWindow", "下载全部"))
        self.savepath_btn.setText(_translate("MainWindow", "保存路径"))
        self.set_cookies_btn.setText(_translate("MainWindow", "Cookies"))
        self.action.setText(_translate("MainWindow", "关于"))
