# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cookies.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CookieDialog(object):
    def setupUi(self, CookieDialog):
        CookieDialog.setObjectName("CookieDialog")
        CookieDialog.resize(584, 352)
        self.gridLayout = QtWidgets.QGridLayout(CookieDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(CookieDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cookie_textEdit = QtWidgets.QTextEdit(CookieDialog)
        self.cookie_textEdit.setObjectName("cookie_textEdit")
        self.gridLayout.addWidget(self.cookie_textEdit, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(401, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.ok_btn = QtWidgets.QPushButton(CookieDialog)
        self.ok_btn.setObjectName("ok_btn")
        self.gridLayout.addWidget(self.ok_btn, 2, 1, 1, 1)
        self.cancel_btn = QtWidgets.QPushButton(CookieDialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout.addWidget(self.cancel_btn, 2, 2, 1, 1)

        self.retranslateUi(CookieDialog)
        QtCore.QMetaObject.connectSlotsByName(CookieDialog)

    def retranslateUi(self, CookieDialog):
        _translate = QtCore.QCoreApplication.translate
        CookieDialog.setWindowTitle(_translate("CookieDialog", "设置大会员Cookie"))
        self.label.setText(_translate("CookieDialog", "大会员Cookie："))
        self.ok_btn.setText(_translate("CookieDialog", "确认"))
        self.cancel_btn.setText(_translate("CookieDialog", "取消"))
